[package]
name = "h5-stats-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = {version = "1.10.0", features = ["v4", "serde"] }
strum = { version = "0.26.3", features = ["derive"] }